create or replace 
FUNCTION VarSample(input NUMBER) RETURN NUMBER PARALLEL_ENABLE
AGGREGATE USING VARIANCJA;


SELECT  DEPARTMENT_ID, VAR_SAMP(SALARY) FROM 
HR.Employees
GROUP BY DEPARTMENT_ID ORDER BY DEPARTMENT_ID;
SELECT DEPARTMENT_ID, 
VarSample(SALARY) FROM HR.Employees GROUP BY DEPARTMENT_ID ORDER BY DEPARTMENT_ID;