DECLARE
  P_FIRST_NAME VARCHAR2(20);
  P_LAST_NAME VARCHAR2(25);
  P_EMAIL VARCHAR2(25);
  P_PHONE_NUMBER VARCHAR2(20);
  P_HIRE_DATE DATE;
  P_JOB_ID VARCHAR2(10);
  P_SALARY NUMBER;
  P_COMMISSION_PCT NUMBER;
  P_MANAGER_ID NUMBER;
  P_DEPARTMENT_ID NUMBER;
BEGIN
  P_FIRST_NAME := NULL;
  P_LAST_NAME := NULL;
  P_EMAIL := NULL;
  P_PHONE_NUMBER := NULL;
  P_HIRE_DATE := NULL;
  P_JOB_ID := NULL;
  P_SALARY := NULL;
  P_COMMISSION_PCT := NULL;
  P_MANAGER_ID := NULL;
  P_DEPARTMENT_ID := NULL;

  INSERTEMPLOYEE(
    P_FIRST_NAME => P_FIRST_NAME,
    P_LAST_NAME => P_LAST_NAME,
    P_EMAIL => P_EMAIL,
    P_PHONE_NUMBER => P_PHONE_NUMBER,
    P_HIRE_DATE => P_HIRE_DATE,
    P_JOB_ID => P_JOB_ID,
    P_SALARY => P_SALARY,
    P_COMMISSION_PCT => P_COMMISSION_PCT,
    P_MANAGER_ID => P_MANAGER_ID,
    P_DEPARTMENT_ID => P_DEPARTMENT_ID
  );
--rollback; 
END;
